language: node_js
node_js:
  - "10"
cache:
  directories:
    - "node_modules"
install:
  - npm install
script:
  - npm run build
  # run SonarQube analysis
  - npm run sonar -- -Dsonar.login=${SONAR_TOKEN}
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN # Set in travis-ci.org dashboard, marked secure
  keep-history: false
  local-dir: "dist"
  on:
    branch: master # only deploy changes from the master branch
