import Vue from 'vue';
import 'vuetify/src/stylus/app.styl';
import Vuetify, {
    VApp,
    VBtn,
    VCard, VDialog,
    VDivider,
    VFooter,
    VIcon,
    VList,
    VContainer,
    VNavigationDrawer,
    VSubheader,
    VLayout,
    VContent,
    VToolbarSideIcon,
    VCardTitle,
    VCardText,
    VFlex,
    VTextField, VToolbar,
    VListTile,
    VListTileTitle,
    VListTileSubTitle,
    VListTileContent,
    VCardActions,
    VSpacer,
    VListTileAction,
} from 'vuetify/lib';

Vue.use(Vuetify, {
    components: {
        VApp,
        VNavigationDrawer,
        VFooter,
        VList,
        VBtn,
        VIcon,
        VToolbar,
        VCard,
        VLayout,
        VContainer,
        VToolbarSideIcon,
        VContent,
        VFlex,
        VDivider,
        VSubheader,
        VCardText,
        VCardTitle,
        VTextField,
        VDialog,
        VListTile,
        VListTileTitle,
        VListTileSubTitle,
        VListTileContent,
        VCardActions,
        VSpacer,
        VListTileAction,
    },
    iconfont: 'md',
});
